return {
  std = "lua53",
  globals = {
    "CenterMarker",
    "CenterMarkerDB",
    "CreateFrame",
    "UIParent",
    "GetAddOnMetadata",
    "GetAddOnInfo",
    "C_ChallengeMode",
    "DEFAULT_CHAT_FRAME",
    "ChatFrame1",
    "GameTooltip",
    "IsInInstance",
    "LoggingCombat",
    "C_AddOns",
    "GetInstanceInfo",
    "InCombatLockdown",
    "UnitAffectingCombat",
    "STANDARD_TEXT_FONT",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_SetSelectedValue",
    "UIDropDownMenu_SetWidth",
    "UIDropDownMenu_CreateInfo",
    "ColorPickerFrame",
    "SlashCmdList",
    "SLASH_CENTERMARKER1",
    "SLASH_CENTERMARKER2",
    "unpack",
  },
  -- Increase max line length to reduce noise; can be tightened later
  max_line_length = 160,
}
